[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "LS-MAT"
authors = [{name = "HoKyun Kim", email = "ghrbs0467@korea.ac.kr"}]
dynamic = ["version", "description"]
